jobs:
  include:
    - stage: test
      sudo: required
      git:
        quiet: true
      services:
        - docker
      before_install:
        - docker build -t orlando10/conways-test -f ./client/Dockerfile.dev ./client
      script:
        - docker run -e CI=true orlando10/conways-test npm run test
    - stage: deploy
      sudo: required
      git:
        quiet: true
      env:
        global:
          - TRAVIS_BUILD_DIR = ./client
      branches:
        only:
          - master
      language: node_js
      node_js:
        - "10"
      dist: trusty
      install:
        - npm install
      script:
        - nohup npm run build &
        - sleep 3
      deploy:
        provider: s3
        region: "us-east-2"
        bucket: "conway-game-of-life-lambda"
        on:
          branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
          secure: "$AWS_SECRET_KEY"
        skip_cleanup: true
        local_dir: build
stages:
  - test
  - name: deploy
    if: branch = master AND type = push