version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
  tests:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    command: ["npm", "run", "test"]